#pragma once
#include "PCNLayer.h"
#include <vector>

namespace Deep
{
    class PCNetwork
    {
    public:
        PCNetwork() = default;
        ~PCNetwork();

        void AddLayer(size_t inSize, size_t outSize, float lr = 1e-6, float ir = 1e-6, int stepSize = 30, ActivationFn act = relu) noexcept {
            layers.emplace_back(inSize, outSize, lr, ir, stepSize, act);
        }

        void AddLayer(PCLayer &&layer) {
            layers.push_back(std::move(layer));
        }

        /// @brief Allocates the layers' memory contiguously for increased cache locality. Not doing this will result in poor performance.
        /// @note It is always recommended you call this before running training.
        void Compile() noexcept;

        /// @brief Appends either x to the bottom layer and propagates upwards, or appends target to the top layer and propagates downwards.
        /// @param x Input (or `nullptr` if target exists)
        /// @param target Target (or `nullptr` if target exists)
        void TrainStep(float *x, float *target);

        /// @brief Appends either x to the bottom layer and runs inference cycles upwards, or appends target to the top layer and runs inference cycles downwards.
        /// @param x Input (or `nullptr` if target exists)
        /// @param target Target (or `nullptr` if target exists)
        void RunPrediction(float *x, float *target);

        /// @brief Runs the last few iterations of an inference cycle not caught in the batch size.
        void Flush();

        /// @brief Returns the energy generated by an inference cycle
        /// @return Energy
        /// @warning Not tested completely yet! Do not rely on this currently.
        float GetTotalEnergy() const noexcept;

        /// @brief Saves the model's array `arr` to the path.
        /// @param path File path
        void SaveModel(const char *path) const noexcept;
        /// @brief Loads the model's array `arr` from the path.
        /// @param path File path
        void LoadModel(const char *path) noexcept;

        #ifdef _DEBUG
        void DebugStats();
        #endif

    private:
        size_t arenaSize;
        size_t pendingCount = 0;
        std::vector<PCLayer> layers;
        float *masterArena;
    };
}